"""
Step 2: Inference API for the Toxic Comment Classifier
---------------------------------------------------------
Goal: Wrap the trained model (model.joblib + vectorizer.joblib) in a small,
production-style FastAPI service.

Why FastAPI?
- Async-friendly, fast, and has automatic interactive docs (Swagger UI) for free
- Widely used in real ML-serving systems, so it's a credible interview talking point
- Type-validated request/response models (via Pydantic) catch bad input early

HOW TO USE:
1. Make sure model.joblib and vectorizer.joblib exist in this folder
   (generated by train_baseline_model.py)
2. Run: pip install fastapi uvicorn pandas scikit-learn joblib
3. Run: uvicorn inference_api:app --reload
4. Open http://127.0.0.1:8000/docs in your browser to test it interactively
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
import joblib
import os

LABEL_COLUMNS = ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]

app = FastAPI(
    title="Content Moderation API",
    description="Classifies text into toxicity categories using a trained ML model.",
    version="1.0.0",
)

# --- Load model artifacts once, at startup (not per-request!) ---
# Loading per-request would be a major performance mistake worth mentioning
# in an interview as a "what NOT to do" example.
vectorizer = None
model = None


@app.on_event("startup")
def load_model():
    global vectorizer, model
    if not os.path.exists("vectorizer.joblib") or not os.path.exists("model.joblib"):
        raise RuntimeError(
            "Model files not found. Run train_baseline_model.py first "
            "to generate vectorizer.joblib and model.joblib."
        )
    vectorizer = joblib.load("vectorizer.joblib")
    model = joblib.load("model.joblib")
    print("Model and vectorizer loaded successfully.")


# --- Request / Response schemas (Pydantic gives us free validation) ---
class ModerationRequest(BaseModel):
    text: str = Field(..., min_length=1, max_length=5000, description="Text to moderate")


class ModerationResponse(BaseModel):
    text: str
    scores: dict           # e.g. {"toxic": 0.87, "threat": 0.02, ...}
    flagged_categories: list  # categories that crossed the threshold
    is_flagged: bool       # true if ANY category crossed the threshold


# Threshold above which we consider a category "flagged".
# 0.5 is a reasonable default; in a real system this would be tuned per category
# based on precision/recall trade-offs (worth mentioning in an interview!).
FLAG_THRESHOLD = 0.5


@app.get("/health")
def health_check():
    """Simple health check endpoint - useful for load balancers / uptime monitors."""
    return {"status": "ok", "model_loaded": model is not None}


@app.post("/moderate", response_model=ModerationResponse)
def moderate_text(request: ModerationRequest):
    """Classify a piece of text across all toxicity categories."""
    if model is None or vectorizer is None:
        raise HTTPException(status_code=503, detail="Model not loaded yet.")

    # Transform input text using the SAME vectorizer used during training
    text_vec = vectorizer.transform([request.text])

    # predict_proba returns probabilities per label
    probabilities = model.predict_proba(text_vec)[0]

    scores = {
        label: round(float(prob), 4)
        for label, prob in zip(LABEL_COLUMNS, probabilities)
    }

    flagged = [label for label, prob in scores.items() if prob >= FLAG_THRESHOLD]

    return ModerationResponse(
        text=request.text,
        scores=scores,
        flagged_categories=flagged,
        is_flagged=len(flagged) > 0,
    )


# Allows running with: python inference_api.py  (in addition to uvicorn command)
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)